// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_client_container`

Future<String> login({
  required String homeserverUrl,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiAuthLogin(
  homeserverUrl: homeserverUrl,
  username: username,
  password: password,
);

Future<void> logout() => RustLib.instance.api.crateApiAuthLogout();
