// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_room_messages`

Future<List<RoomMessage>> getRoomMessages({required String roomId}) =>
    RustLib.instance.api.crateApiMessagesGetRoomMessages(roomId: roomId);

Future<void> sendMessage({required String roomId, required String body}) =>
    RustLib.instance.api.crateApiMessagesSendMessage(
      roomId: roomId,
      body: body,
    );

Stream<List<RoomMessage>> watchRoomMessages({required String roomId}) =>
    RustLib.instance.api.crateApiMessagesWatchRoomMessages(roomId: roomId);
