// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

class RoomMessage {
  final String eventId;
  final String sender;
  final String body;
  final PlatformInt64 timestamp;

  const RoomMessage({
    required this.eventId,
    required this.sender,
    required this.body,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^ sender.hashCode ^ body.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomMessage &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sender == other.sender &&
          body == other.body &&
          timestamp == other.timestamp;
}

class RoomSummary {
  final String roomId;
  final String name;

  const RoomSummary({required this.roomId, required this.name});

  @override
  int get hashCode => roomId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name;
}
